### ISSUE TITLE
I am unable to get results

### ISSUE THREAD

**Issue by Guitarflier** [DavideViolante/investing-com-api#120]
Hallo, I appreciate your work and I really would like to be able to use for retieving data, but unfortunately in my case I can't.
What I did so far:
`npm i investing-com-api`
(warn on finishing about puppeteer version deprecated...)
Created a myfile.js file with content as for your example.
Launched myfile.js with:
`node myfile.js`
The script runs with no errors, but nothing appears as result on the terminal.
Am I missing something?
Thank you.

**Comment by DavideViolante** [comment]
Please paste here your code thank you.

**Comment by Guitarflier** [comment]
I tried:

const { investing } = require('investing-com-api');
async function main() {
  try {
    const response = await investing('currencies/eur-usd'); // Providing a valid mapping.js key
    console.log(response);
  } catch (err) {
    console.error(err);
  }
}

I also tried the other 2 options in your example, and also with
` console.log(response.data);`

My terminal remains desperately wordless...😅

**Comment by DavideViolante** [comment]
add `main();` at the end of this file to call the function.

```ts
const { investing } = require('investing-com-api');
async function main() {
  try {
    const response = await investing('currencies/eur-usd'); // Providing a valid mapping.js key
    console.log(response);
  } catch (err) {
    console.error(err);
  }
}

main(); // <-- you have this?
```

**Comment by Guitarflier** [comment]
It was missing, I added.
Now this is response launcihng my .js (3 times, you never know...)
![Screenshot 2024-01-10 at 18 18 28](https://github.com/DavideViolante/investing-com-api/assets/10785805/291e879c-f964-47b3-8718-b6526379fe96)

**Comment by DavideViolante** [comment]
I also get the warning but I also get the results printed below the warning.
Idk honestly, can you upload the whole code project? There should be at least an error if something is wrong.
Can you try just a normal console.log('hello') in your code and check if this is printed?
Also try maybe another npm package and check if it works as expected.
Also tell me your node version.

**Comment by Guitarflier** [comment]
Ok, I got it now.

**Comment by DavideViolante** [comment]
Don't worry about the warning.
If you really want to remove it:

`investing('currencies/eur-usd', 'P1M', 'P1D', 120, { headless: 'new' });`

**Comment by Guitarflier** [comment]
Grazie, you can close. Buon Anno!
