### ISSUE TITLE
Where is the header?

### ISSUE THREAD

**Issue by joelwang13** [DavideViolante/investing-com-api#67]
Hi Davide, 
I use python to get data from the same url: https://api.investing.com/api/financialdata/8830/historical/chart/? as yours. Where can I find your API header? I am wondering if the api still work, because my crawler returns " Enable JavaScript and cookies to continue".
THX!

**Comment by DavideViolante** [comment]
I'm not currently passing any header. 
I think the issue is related to #68

**Comment by DavideViolante** [comment]
This should be fixed in the PR #69 where I'm using Puppeteer instead of Axios. Can you try if this is working for you @joelwang13 ?
