### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by baedaron** [DavideViolante/investing-com-api#68]
OS: Windows 10 Pro 21H1
Node.js: node-v14.20.0-win-x64

==================================================================
Welcome to Node.js v14.20.0.
Type ".help" for more information.
> .load ../test.js

const { investing } = require('investing-com-api');

async function main() {
  try {
      const response1 = await investing('currencies/eur-usd');
          const response2 = await investing('currencies/eur-usd', 'P1M', 'P1D'); // With optional params
   } catch (err) {
          console.error(err);
   }
}

main();

Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 95,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
**> Request failed with status code 403
Request failed with status code 403**

**Comment by DavideViolante** [comment]
Thanks for reporting, I will investigate asap.

**Comment by baedaron** [comment]
1. When I tried below URL with Microsoft Edge, there was no problem.
2. When I tried the same URL with Apache HttpClient(Java), it printed below "Response Headers" and "Response Body".
3. I think this problem has a relation to CORS(Cross-Origin Resource Sharing).
4. Probablely there should be a way, if the javascripts in the "Response Body" could be executed in NodeJS.

==================== Request URL & Method ====================
GET: https://api.investing.com/api/financialdata/1/historical/chart/?period=P1M&interval=P1D&pointscount=120

==================== Response Headers ====================
HTTP/1.1 403 Forbidden
Date: Tue, 20 Sep 2022 09:15:49 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
CF-Chl-Bypass: 1
Permissions-Policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 01 Jan 1970 00:00:01 GMT
X-Frame-Options: SAMEORIGIN
Set-Cookie: __cf_bm=oEJ0IU8TS5lnK2UB3DKzJMZ7yPuPICmmmwk1ipC2Uqk-1663665349-0-AbicxoR0LBsQKDE6Pyr1J5mN6Pp/EtCTyCWR+L/f4PX2iIXNWHBwKjEIZaWR0TOOoCK/oJORn4ZL624jbdM3nxg=; path=/; expires=Tue, 20-Sep-22 09:45:49 GMT; domain=.investing.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
Server: cloudflare
CF-RAY: 74d97573fd48c10a-ICN
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

==================== Response Body ====================
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="robots" content="noindex,nofollow" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet" />
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)" />
            api.investing.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=74d97573fd48c10a')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            api.investing.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/financialdata/1/historical/chart/?period=P1M&amp;interval=P1D&amp;pointscount=120&amp;__cf_chl_f_tk=PG9gp9TWGMTzzz8ZJeiWOrTvCrP0H8fq5M8vCuKEpjI-1663665349-0-gaNycGzNBj0" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="MG0KxqZPPkuij67YRAbKB5ln_2LHWMNhJH_ZLcVwmZ4-1663665349-0-AdMhmTzbkjY5AUuOp1PO_mrQfzSMSOCYe6_rfRHbfriXVf-YvVXlWn-AYEKlzMIYdi0QZFtAlbn15BnUVQdnF4JpGCxpq1XQOFeMyA-dlOPppPH_hzDO4JHfp8OVJUCpoohTXMj_y-qkVKiZ2HdWAjSj1V0a_lvt0t_RnRL_VCdqqygfvynx6GxPl7_R-35C5utNB9r3Fa0mrNI-R9WtQdMlHjdOfopBu5Hm3FlAfXSvrHUt6PpF-EGRWK4XTitWKkuzHPxB8R6CpcMaooAzre2xu6KEJsKiE2V0Y4cXkl_WNtfyf7xebWlT8BMic_wVzmmgX-DSjR10Zv6ZrCt6YeQMw-PE0scgSPv2LorjilNYBotzFeB_prHeKV7yOM5ZjGK3QRQsHOrDVPS83jvx6tAOH5yiehXvEC90Z-2dhuANVmS9aQz8nuD7kBqg7FBeBbHDcP5u0O6VZkA6VzornEpAfyQ39NbQxyKvTbj4RizPkPZsCkSNHEFyyE4lG8ppj5wSQ8WXkc4DTLALEccLM3WWGCa_w0WTcOjQD2fg9jeA_2oncTCfE6A7fKRBqmz3a0KeVYHNrFsMQRAISt1uUowD6Word801XmjQv1UcHPFDuYU-ANOnwMRYPlMLXi17_XzJVfjNBiSbpDuyuFNnMId9cGQMCgwBRhF7qpofNI9o2l_D0mbhEJG3VAgVxRSdQvU-ah7QUo_lLKNJWrTor3f3BJhTlchDCw4TKnzW4G0XWSJ0h-pf0EHrmLFWkfHy1F-jn_Io1XduhC3VdpxRo_NPkv4e1EQ4o5tvszT9S983hWjhMD9GBfRXDe7phFUtA7mHz2rOv1iIM0B-05ec8iXohTbAQRM3qHF2a1wrCQXWpGIoSmOASje29gJRNLgRNrnOSParXNw4f_jcKpnowEA" />
            <input type="hidden" name="r" value="jLmrkowurYjUJVFYzvvAnUF.G0smzReFe1NU1TSW1Wc-1663665349-0-ARnYkHV/3K1/IOsoizaoDIgYY40Y+k1fyN7YaeqYxVGa5kA8Rgyhy3cwKoJh0FPivSByDuTO6KdsGCLXTvw/EXgSlzuARawrD2R1zoMyxtFRTVkh3K3RJghB4Rllybz1nlzGyWP666+BJiognm7y/jTqfZuyVIaaoNh0Tyg7DPXi74Yr+lmDXZjlxvrnN/MoFeGsiHjnQuNuz2+FRTsGTRgWVsjOdH2+6mHTKloxSonLKALcHkE+Elcw1gZSmTcOvwU27Lmx4xGkRjrnIcTyb8Do6rjBXlp0PFF4ky2sw0e6nSDdSs2tozMKZtzhxPqb+fZuydeIOTQe+z8JHU9liyC6uhggOAJs2U/LE1OSo81ZoY057U1LH1lAc3lRi7EnmgbEo7krvZO4KXUCVcbp+lzMN6ig+Y+XLudDQl2rbcQGdywO8JKUAYnOK/twWLbmgpSp6m2lHLkOHZ2xtBaj7Gux5D7kd8GwQtT+G9kW/f/uHaUtYSmTo7SWkTL/JMtnd9iXNfnh+Ej/lpgnaYzgZLdZmAzmHntUawyJb+0Lfyz/vtqZFuEHzR98qC/LAL6ARE/jo+Jr0WcaajnNIWg5457GapfrcT5yCobhKI4g+tPhkYPnPSDpfCEqLzF1CojPzcyU48gFk8swKNI5R1zZj7wU0toQd8IC5912DR/rqdX4l8yZ3zujnQex6J4qaT40TgtKseRyQmId3YWTz8oOQlfG1bII93cF1qXt3wrdhLi1poW1NmKUD1M3f4/s3oeSoDuhlvcxRAa5x1mwkWitLE5K53HcHHKrBAYFRA+PW7Likiqtl90io1868Lzr+u+D1vNLmlm0n523F9MJ0s9IMWyLtbno8OZAzPI02oEbDHvxx9F+YRci0nYyuQ/sIEkSuJFhLl6Qt6yikZjsijMBx7M7C3bnuyOCUUN4iwhiAZKHDloGcTECs29fTD/Bx1etLvBgH4CPhpMJuN1Ui+mEb7HRikJOuL4qgUrwKFEZX9iAW4TU7TW4Q4+B43lpaEUkyNElqg3nApMBS00P0nWM+dK1q1SHz0DaN3qJCLw7xJqZioehRZR/cqO5yeGPbAHEsbkGOz6yQC+HjcI3sRNrjzeptz8EBo8ognCi1uDKhc/pnLZc9WAr1MKc1xi49y1N6LNFVQ46unNZKjw5iZrliiJcK7SGd6B/9FGB7M47qcBGvUpruL0HbDjO8nBDU5tyiOWKzX18535s2F3GX3+rVV6rlTCvrLPo83qaQAQAkbdbjVq5weXNBVEWOq+uNRunQTpbKBXe4sLOhvkzdk/JgmNsaJeVlJzQS9CV+ukPtv+6/1j+z4iD/zZ6kSQmpsT+Z37mRc0gqrlP+SaMGSuZ80XJVE/yxROUICcY+Gvfc8OrjTsR4tJfjUnQirKZ41T/eyWT1TVt/IauP5+ZiaGP5rXeu6xwuGQUBXFuAaImjZBp8y97RbiknPjd+Z4jNhO2ygoqi1aCe+AvH9iKJP3WhYXlumISzGqGz2GzL5dQVcWBvvUAzB3HzWSkcidxNmN6dA=="/>
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'managed',
            cNounce: '61144',
            cRay: '74d97573fd48c10a',
            cHash: 'd26e6375b1813ec',
            cUPMDTk: "\/api\/financialdata\/1\/historical\/chart\/?period=P1M&interval=P1D&pointscount=120&__cf_chl_tk=PG9gp9TWGMTzzz8ZJeiWOrTvCrP0H8fq5M8vCuKEpjI-1663665349-0-gaNycGzNBj0",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly9hcGkuaW52ZXN0aW5nLmNvbS9hcGkvZmluYW5jaWFsZGF0YS8xL2hpc3RvcmljYWwvY2hhcnQvP3BlcmlvZD1QMU0maW50ZXJ2YWw9UDFEJnBvaW50c2NvdW50PTEyMA==',
                ra: 'QXBhY2hlLUh0dHBDbGllbnQvNC41LjEzIChKYXZhLzEuOC4wXzI4MSk=',
                rm: 'R0VU',
                d: '2IeQIv1Ec+6A90MHh5ylj2ruEOSfsFK60fPjJ/jRnkb3P5/VNJoM9x4VPEl78kA3HyGxKbmwGA0lpho41GzFWfaQWwqub+tl0dmGjFkuilYUgWbbiaG6Nurcqi13pCLWPKoL+9YcnzqMElxkhqC+NpEF1MjfTfPaka547eBXW1VnMUQGpyinlrmty7VSS12VnVuR0V/CaUaFXHHm0xCGorUJrObU0lmw9p7LuwVMp5uzpVPKssA/LVyH5ZT0CXCh+Hm5x8X1siy7BFN/gAia5gcu/WyejeFTo8yoWYs9G/K4u1coc9l7vCaDGhR3R1bC8QQNTlzO+XoRc23OJOlxjnal50cmBalAYednY78/st605rzvU7bV0v2MnbE9jfhbvqI2cQhEeJlMgq3NMAIhFZdbRUZ8OyzJWurb7r722UTmncIIP+KAqr2oOt5QQhcbmNyd7lhvGTLF/Cjhzt7s8JNQswrE7nDpo9GeIoY3HKdEc0JfeCoNbU4IuXSNrFTtLwonBI9wU3D3f9KeSTZW93XLddo3yST2g0wCfcYlyS09ikExs9UonziX4woA6mTyJ0cYV1uwPu0dZtsagBPpviy2+Mq05t3hbY0K3gVwa3tr0aY/KET4Lac+8aKlhQd9kfRwMhMQ6cSw3jUnOmVQMOQN8f+aXYLTnXN5QI1pevKPwhg8FT3gcH8XAZIo3VgX',
                t: 'MTY2MzY2NTM0OS43NjMwMDA=',
                m: 'vRzfm76nvzZtesyb5F3u2x0/zZ+YNkwyloWoCI1quL8=',
                i1: 'bqJKMpEpih+Fsi8fNBqkUQ==',
                i2: 'DvihXQOlE56mO/Eg11MIHg==',
                zh: 'JJQg2KI/+bPgJbLHlLjmrs/mnno8aAGH5k3tm8QDk4c=',
                uh: '5Kd8TTnp2AWR261gwo9q1dGTBfc8by0s0tFS5/ToeCs=',
                hh: 'TfRt9Pa+nZmMjzaNtqKhPewDA77wlx9goxuG3yqio+0=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=74d97573fd48c10a');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=74d97573fd48c10a';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/financialdata\/1\/historical\/chart\/?period=P1M&interval=P1D&pointscount=120&__cf_chl_rt_tk=PG9gp9TWGMTzzz8ZJeiWOrTvCrP0H8fq5M8vCuKEpjI-1663665349-0-gaNycGzNBj0" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>74d97573fd48c10a</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>

**Comment by playmast3r** [comment]
This can be bypassed if API is called via Puppeteer or implementing Google BoringSSL for curl (used internally by google chrome).
IMO Puppeteer will be a heavy and resource-hungry solution.

**Comment by DavideViolante** [comment]
I tried using Puppeteer and released a v4.0.0, let me know if this works correctly, thank you.

@playmast3r how would you fix it with BoringSSL? I didn't understand.

**Comment by baedaron** [comment]
..\node-v16.17.0-win-x64\npm install investing-com-api

npm ERR! code 1
npm ERR! path C:\Users\Administrator\Downloads\node_test\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c R:\Temp\install-389d646d.cmd
npm ERR! 'node'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
npm ERR! ��ġ ������ �ƴմϴ�.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-09-21T17_15_54_757Z-debug-0.log

===============2022-09-21T17_15_54_757Z-debug-0.log====================
.
.
.
419 http fetch GET 200 https://registry.npmjs.org/investing-com-api/-/investing-com-api-4.0.0.tgz 370ms (cache miss)
420 timing reifyNode:node_modules/investing-com-api Completed in 436ms
421 http fetch GET 200 https://registry.npmjs.org/devtools-protocol/-/devtools-protocol-0.0.1036444.tgz 393ms (cache miss)
422 timing reifyNode:node_modules/devtools-protocol Completed in 453ms
423 http fetch GET 200 https://registry.npmjs.org/@types/node/-/node-18.7.18.tgz 471ms (cache miss)
424 timing reifyNode:node_modules/@types/node Completed in 519ms
425 http fetch GET 200 https://registry.npmjs.org/puppeteer/-/puppeteer-18.0.4.tgz 1262ms (cache miss)
426 timing reifyNode:node_modules/puppeteer Completed in 1327ms
427 timing reify:unpack Completed in 1329ms
428 timing reify:unretire Completed in 0ms
429 timing build:queue Completed in 5ms
430 timing build:link:node_modules/rimraf Completed in 11ms
431 timing build:link:node_modules/extract-zip Completed in 12ms
432 timing build:link Completed in 12ms
433 info run puppeteer@18.0.4 install node_modules/puppeteer node install.js
434 info run puppeteer@18.0.4 install { code: 1, signal: null }
435 timing reify:rollback:createSparse Completed in 724ms
436 timing reify:rollback:retireShallow Completed in 1ms
437 timing command:install Completed in 7258ms
438 verbose stack Error: command failed
438 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\Downloads\node-v16.17.0-win-x64\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
438 verbose stack     at ChildProcess.emit (node:events:513:28)
438 verbose stack     at maybeClose (node:internal/child_process:1093:16)
438 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
439 verbose pkgid puppeteer@18.0.4
440 verbose cwd C:\Users\Administrator\Downloads\node_test
441 verbose Windows_NT 10.0.19043
442 verbose node v16.17.0
443 verbose npm  v8.15.0
444 error code 1
445 error path C:\Users\Administrator\Downloads\node_test\node_modules\puppeteer
446 error command failed
447 error command C:\Windows\system32\cmd.exe /d /s /c R:\Temp\install-389d646d.cmd
448 error 'node'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
448 error ��ġ ������ �ƴմϴ�.
449 verbose exit 1
450 timing npm Completed in 7354ms
451 verbose unfinished npm timer reify 1663780554848
452 verbose unfinished npm timer reify:build 1663780561329
453 verbose unfinished npm timer build 1663780561330
454 verbose unfinished npm timer build:deps 1663780561330
455 verbose unfinished npm timer build:run:install 1663780561347
456 verbose unfinished npm timer build:run:install:node_modules/puppeteer 1663780561347
457 verbose code 1
.
.
.

**Comment by DavideViolante** [comment]
I tried by myself and it seems to work for me. Using Node v16, investing-com-api v4.0.0 and this code
```js
const { investing } = require('investing-com-api');

async function inv() {
  const res = await investing('currencies/eur-usd');
  console.log(res);
}

inv();
```

Can somebody confirm v4 it's actually working fine?

**Comment by Tainoko** [comment]
It worked for me.
If it doesn't work, check out Troubleshooting in puppeteer.
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
