### ISSUE TITLE
Add Playwright (the successor of Puppeteer) in addition to Puppeteer

### ISSUE THREAD

**Issue by baedaron** [DavideViolante/investing-com-api#73]
hi,

i am using Playwright for Java(https://playwright.dev/).
and Playwright supports NodeJS primarily.
if you can do, it will be a big help for me.

thanks.

**Comment by DavideViolante** [comment]
I don't understand exactly what's your goal. Playwright is used for writing end to end _tests_, Puppeteer is used to simulate a web browser (that's why I used in this project). I think the goal of these 2 are different. Explain better your issue, thanks.

**Comment by baedaron** [comment]
In short, I need a Java version of something just like investing-com-api (v4.0+, the Puppeteer patched version).
I am struggling with Playwright to resolve the problem which you've encountered with v4.0- version,
because Puppeteer  dose not provide Java API.
In my current knowledge, only Playwright provide Java API.
I have no concept what "end to end tests" is, though.
So I wanted to get a hit from your skill, if you implements Playwright version of investing-com-api.
https://github.com/DavideViolante/investing-com-api/issues/68

**Comment by DavideViolante** [comment]
I'm afraid I will not release any Java version since I don't have enough knowledge of that language and Playwright. I think you can try the Playwright example code and replace the URL with investing one llike this repo.

**Comment by baedaron** [comment]
You need not release Java version of investing-com-api.
Just release NodeJs version of "investing-com-api with Playwright" if possible!
Then I will very very very much thank you~~~ :)
When I can read your Playwright-patched investing-com-api, God will soak into my head and everything shall be resolved.... :)

**Comment by baedaron** [comment]
found a way.
https://github.com/microsoft/playwright/issues/5992

thanks, anyway.
