### ISSUE TITLE
Need solution for manual input pairId if fetch item not exists in mapping.js

### ISSUE THREAD

**Issue by JimmyHwang** [DavideViolante/investing-com-api#81]
I would fetch "38017" from intesting, but the code not exists in mapping.js
We can't put whole codes into mapping.js, so I will prefer have a solution let user input a object instead of name
By Example:
   Copy "input" into "endpoint" if "input" parameter is object type.

**Comment by DavideViolante** [comment]
That's interesting suggestion, thank you. Please try the v4.3.0 version and let me know.
Changes: https://github.com/DavideViolante/investing-com-api/commit/cbf0bb1de1130dbeeec1c8e639e18e8d6187fb41

**Comment by JimmyHwang** [comment]
@DavideViolante, Thanks, it is work well on 4.3.0   👍
