### ISSUE TITLE
Need a solution to bypass args for launch pupperteer

### ISSUE THREAD

**Issue by JimmyHwang** [DavideViolante/investing-com-api#82]
Current;y, I need run my system as root user, so I need made hardcode add "--no-sandbox" in index.js for puppeteer, Could we have solution let user easy add the parameters when launch time.

Example code:
const browser = await puppeteer.launch(**{args: ["--no-sandbox"]}**);

**Comment by DavideViolante** [comment]
I can't understand your use case. Adding no-sandbox is [discouraged](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) by puppetteer.
What is your goal and why you can't use with sandbox?

**Comment by DavideViolante** [comment]
Mmh, if you need to run the service as background I recommend to use a cronjob that runs a small node.js script that implements this library. I'm not understanding how you are running the service in background and why as root user.
I'm not planning to add this change for this edge case, I recommend to fork the project and do the change.

**Comment by JimmyHwang** [comment]
Well, thanks for comments, I will try other better solution.
