### ISSUE TITLE
Add parameter to specify Puppeteer launch options for use in Docker

### ISSUE THREAD

**Issue by basvdijk** [DavideViolante/investing-com-api#90]
When running in a Docker container we need to specify Puppeteer launch options in order to make Puppeteer work:

```
  const browser = await puppeteer.launch({
    executablePath: '/usr/bin/google-chrome',
    args: [
      '--disable-gpu',
      '--disable-dev-shm-usage',
      '--disable-setuid-sandbox',
      '--no-sandbox',
    ],
  })
```
See https://pptr.dev/api/puppeteer.launchoptions for all options.

Currently there is no way to specify these launch options.

**Comment by DavideViolante** [comment]
Please try v4.3.2
